.unittests: # Hidden, thus not executed
  stage: test
  script:
    - pip install coverage
    # allow this to fail in order to generate coverage report
    - coverage run -m unittest discover --pattern='*tests.py' || true
    - coverage report --omit="venv/*","tests/*","webapp/*"
    # this actually makes the pipeline fail if tests don't pass
    - python -m unittest discover --pattern="*tests.py"
  parallel:
    matrix:
      - version: [weekend-1]
  coverage: '/TOTAL.*\s+(\d+\%)/'

# Use of '@dataclass' requires Python 3.7
# unittests-3.6:
#   extends: .unittests
#   image: python:3.6

unittests-3.7:
  extends: .unittests
  image: python:3.7

unittests-3.8:
  extends: .unittests
  image: python:3.8

unittests-3.9:
  extends: .unittests
  image: python:3.9

unittests-3.10:
  extends: .unittests
  image: python:3.10

unittests-3.11:
  extends: .unittests
  image: python:3.11

unittests-3.12:
  extends: .unittests
  image: python:3.12
