.unittests: # Hidden, thus not executed
  stage: test
  script:
    - cd project/$version
    - python -m unittest discover --pattern=unittests.py
  parallel:
    matrix:
      - version: [weekend-1]

unittests-3.6:
  extends: .unittests
  image: python:3.6

unittests-3.7:
  extends: .unittests
  image: python:3.7

unittests-3.8:
  extends: .unittests
  image: python:3.8

unittests-3.9:
  extends: .unittests
  image: python:3.9

unittests-3.10:
  extends: .unittests
  image: python:3.10

unittests-3.11:
  extends: .unittests
  image: python:3.11

unittests-3.12:
  extends: .unittests
  image: python:3.12
